name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -G "Unix Makefiles" .
    - name: make
      run: cmake --build .
